# Generated by Django 2.1.7 on 2019-05-06 20:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('compID', models.CharField(blank=True, max_length=50, null=True, verbose_name='公司ID')),
                ('modalName', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备名称')),
                ('machCode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='设备编码')),
                ('des', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备描述')),
                ('gateMac', models.CharField(blank=True, max_length=50, null=True, verbose_name='网关Mac')),
                ('protocol', models.CharField(blank=True, max_length=100, null=True, verbose_name='协议名称')),
                ('serialPort', models.CharField(blank=True, max_length=50, null=True, verbose_name='端口号')),
                ('operationFlag', models.IntegerField(default=9, verbose_name='标志位')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='设备状态')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物影子',
                'db_table': 'edge_devicemodal',
                'verbose_name_plural': '物影子',
            },
        ),
        migrations.CreateModel(
            name='DeviceTemplates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TemplateName', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='模板名称')),
                ('TypeList', models.CharField(blank=True, max_length=255, null=True, verbose_name='支持协议')),
                ('proType', models.CharField(blank=True, max_length=50, null=True, verbose_name='协议类型')),
                ('operationFlag', models.IntegerField(default=9, verbose_name='是否启用标识符')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建的时间')),
                ('updateTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新的时间')),
            ],
            options={
                'verbose_name': '采集项模板',
                'db_table': 'device_templates',
                'verbose_name_plural': '采集项模板',
            },
        ),
        migrations.CreateModel(
            name='ProtocolDNC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gateMac', models.CharField(blank=True, max_length=50, null=True, verbose_name='网关Mac')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='变量类型')),
                ('operationValue', models.CharField(blank=True, max_length=50, null=True, verbose_name='变量名称')),
                ('operationUnit', models.CharField(blank=True, max_length=50, null=True, verbose_name='变量单位')),
                ('Description', models.CharField(blank=True, max_length=255, null=True, verbose_name='采集项名称的描述')),
                ('deviceIP', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备IP')),
                ('operationFlag', models.IntegerField(default=9, verbose_name='是否启用标识符')),
                ('upload', models.IntegerField(default=0, verbose_name='是否上传DAC')),
                ('configValue', models.CharField(blank=True, max_length=50, null=True, verbose_name='端口号')),
                ('machCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备编码')),
                ('template', models.IntegerField(default=-1, verbose_name='模板ID')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建的时间')),
                ('updateTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新的时间')),
            ],
            options={
                'verbose_name': 'DNC采集项',
                'db_table': 'protocol_dnc',
                'verbose_name_plural': 'DNC采集项',
            },
        ),
        migrations.CreateModel(
            name='ProtocolParamsDNC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ProType', models.CharField(blank=True, max_length=50, null=True, verbose_name='协议名称')),
                ('operationValue', models.CharField(blank=True, max_length=50, null=True, verbose_name='采集项名称')),
                ('Description', models.CharField(blank=True, max_length=255, null=True, verbose_name='采集项名称的描述')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='字段类型')),
                ('configValue', models.CharField(blank=True, max_length=50, null=True, verbose_name='端口号')),
                ('operationUnit', models.CharField(blank=True, max_length=50, null=True, verbose_name='采集项单位')),
                ('operationFlag', models.IntegerField(default=9, verbose_name='标识符')),
                ('upload', models.IntegerField(default=0, verbose_name='是否上传DAC')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建的时间')),
                ('updateTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新的时间')),
            ],
            options={
                'verbose_name': 'DNC协议采集项模板',
                'db_table': 'protocol_params_dnc',
                'verbose_name_plural': 'DNC协议采集项模板',
            },
        ),
        migrations.CreateModel(
            name='ProtocolPLC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gateMac', models.CharField(blank=True, max_length=50, null=True, verbose_name='网关Mac')),
                ('deviceType', models.CharField(blank=True, max_length=50, null=True, verbose_name='协议名称')),
                ('serialNum', models.CharField(blank=True, max_length=50, null=True, verbose_name='网关串口号')),
                ('deviceID', models.CharField(blank=True, max_length=50, null=True, verbose_name='采集设备的协议ID号')),
                ('deviceIP', models.CharField(blank=True, max_length=50, null=True, verbose_name='采集设备的IP')),
                ('functionCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='功能码')),
                ('startAddress', models.CharField(blank=True, max_length=50, null=True, verbose_name='读取寄存器的起始地址')),
                ('len', models.CharField(blank=True, max_length=20, null=True, verbose_name='读取的寄存器个数')),
                ('operationFlag', models.IntegerField(default=9, verbose_name='是否有效标识符')),
                ('delayMs', models.CharField(blank=True, max_length=50, null=True, verbose_name='每次读取数据的延时时间，单位ms')),
                ('machCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备编码')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='变量名字')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='变量类型')),
                ('Multiple', models.CharField(blank=True, max_length=50, null=True, verbose_name='倍数运算')),
                ('offset', models.CharField(blank=True, max_length=50, null=True, verbose_name='补偿运算')),
                ('maxValue', models.CharField(blank=True, max_length=50, null=True, verbose_name='最大值')),
                ('minValue', models.CharField(blank=True, max_length=50, null=True, verbose_name='最小值')),
                ('des', models.CharField(blank=True, max_length=100, null=True, verbose_name='为对应指令描述')),
                ('operationUnit', models.CharField(blank=True, max_length=50, null=True, verbose_name='变量单位')),
                ('template', models.IntegerField(default=-1, verbose_name='模板ID')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建的时间')),
                ('updateTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新的时间')),
            ],
            options={
                'verbose_name': 'PLC采集项',
                'db_table': 'protocol_plc',
                'verbose_name_plural': 'PLC采集项',
            },
        ),
        migrations.CreateModel(
            name='ProtocolType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DeviceType', models.CharField(blank=True, max_length=50, null=True, verbose_name='协议类型')),
                ('TypeList', models.CharField(blank=True, max_length=50, null=True, verbose_name='协议名称_设备版本')),
                ('operationFlag', models.IntegerField(default=9, verbose_name='是否启用标识符')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建的时间')),
                ('updateTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新的时间')),
            ],
            options={
                'verbose_name': '协议类型',
                'db_table': 'protocol_type',
                'verbose_name_plural': '协议类型',
            },
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('compID', models.CharField(blank=True, max_length=20, null=True, verbose_name='公司ID')),
                ('machCode', models.CharField(blank=True, max_length=100, null=True, verbose_name='设备编码')),
                ('gateMac', models.CharField(blank=True, max_length=100, null=True, verbose_name='网关Mac')),
                ('Protocol', models.CharField(blank=True, max_length=20, null=True, verbose_name='协议名称')),
                ('gateWayIP', models.CharField(blank=True, max_length=50, null=True, verbose_name='网关采集的设备IP')),
                ('serial_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='串口号')),
                ('gateWayID', models.CharField(blank=True, max_length=50, null=True, verbose_name='网关采集的设备ID')),
                ('dataType', models.CharField(blank=True, max_length=50, null=True, verbose_name='数据类型')),
                ('operationValue', models.CharField(blank=True, max_length=50, null=True, verbose_name='变量')),
                ('operationData', models.CharField(blank=True, max_length=50, null=True, verbose_name='变量值')),
                ('operationUnit', models.CharField(blank=True, max_length=50, null=True, verbose_name='变量单位')),
                ('gatherTime', models.CharField(blank=True, max_length=50, null=True, verbose_name='数据上传时间')),
                ('operationFlag', models.IntegerField(default=9, verbose_name='数据标志位')),
                ('cpu_usage', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPU使用率')),
                ('mem_usage', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPU使用率')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('machID', models.ForeignKey(db_column='machID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='MatterAnalysis.DeviceModal')),
            ],
            options={
                'verbose_name': '变量表',
                'db_table': 'dac_variables',
                'verbose_name_plural': '变量表',
            },
        ),
        migrations.AddField(
            model_name='protocolplc',
            name='dataType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proPLC', to='MatterAnalysis.ProtocolType'),
        ),
        migrations.AlterUniqueTogether(
            name='protocolparamsdnc',
            unique_together={('ProType', 'operationValue')},
        ),
        migrations.AddField(
            model_name='protocoldnc',
            name='deviceType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proDNC', to='MatterAnalysis.ProtocolType'),
        ),
        migrations.AlterUniqueTogether(
            name='variables',
            unique_together={('machCode', 'operationValue', 'Protocol')},
        ),
        migrations.AlterUniqueTogether(
            name='protocolplc',
            unique_together={('name', 'gateMac', 'template', 'machCode', 'deviceType')},
        ),
        migrations.AlterUniqueTogether(
            name='protocoldnc',
            unique_together={('gateMac', 'operationValue', 'machCode', 'template', 'deviceType')},
        ),
    ]
