# Generated by Django 2.1.7 on 2019-05-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatterAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocoltype',
            options={'verbose_name': '协议类型', 'verbose_name_plural': '协议'},
        ),
    ]
