# Generated by Django 2.1.7 on 2019-05-06 20:03

import apps.DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmDetailsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='算法名称')),
                ('synopsis', models.TextField(blank=True, null=True, verbose_name='算法简介')),
                ('contents', apps.DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='算法内容')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='图标')),
                ('nameEn', models.CharField(blank=True, max_length=255, null=True, verbose_name='算法英文名称')),
                ('inputFormat', apps.DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='输入格式')),
                ('inputJson', apps.DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='输入json文件样式')),
                ('outputJson', apps.DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='输出json文件')),
                ('outputContent', apps.DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='输出内容')),
                ('api', apps.DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='API')),
            ],
            options={
                'verbose_name': '算法详情',
                'db_table': 'algorithm_details',
                'verbose_name_plural': '算法详情',
            },
        ),
        migrations.CreateModel(
            name='AlgorithmTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='算法类型')),
            ],
            options={
                'verbose_name': '算法类型',
                'db_table': 'algorithm_type',
                'verbose_name_plural': '算法类型',
            },
        ),
        migrations.AddField(
            model_name='algorithmdetailsmodel',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='algorithm_types', to='Am.AlgorithmTypeModel'),
        ),
    ]
